[package]
name = "encrypt-files"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
rsa = "0.9.6"
soft-aes = "0.2.2"
zeroize = "1.8.1"

